# Generated by Django 5.0 on 2024-10-26 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_userprofile_saved_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='saved_products',
        ),
    ]
