# Generated by Django 5.0 on 2024-10-29 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_userprofile_saved_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='contact',
            field=models.CharField(default='0000000000', help_text='Enter email or phone number', max_length=100),
        ),
    ]
