# Generated by Django 5.0 on 2024-10-29 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_product_otp_product_otp_expiration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='otp',
        ),
        migrations.RemoveField(
            model_name='product',
            name='otp_expiration',
        ),
    ]
