# Generated by Django 5.0 on 2024-10-29 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_product_otp_remove_product_otp_expiration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='contact',
            field=models.CharField(help_text='Enter email or phone number', max_length=100),
        ),
    ]
